<h2>Profile of ...</h2>
<?php if(isset($this->profileshowDepiction)) : ?> <img class="avatar size128" src="<?= $this->profileshowDepiction ?>" /> <?php endif; ?>
<div class="profile">
    <h3><?= $this->profileshowName ?></h3>
    <?php if(isset($this->profileshowNick)) : ?> <h4><?= $this->profileshowNick ?></h4> <?php endif; ?>
    <h5>knows ...</h5>
    <form method="post" action="?c=profile&a=addfriend">
    <ul>
<?php
foreach($this->profileshowKnows as $contact) :
if ($contact['name'] != null) {
    $name = $contact['name'];
} else {
    $name = $contact['contactUri'];
}
?>
        <li><a href="?c=profile&amp;a=show&amp;person=<?= urlencode($contact['contactUri']) ?>"><?= $name ?></a></li>
<?php endforeach; ?>
        <li>
            <div class="input-append">
                <input type="hidden" name="person" value="<?= $this->profileshowPersonUri ?>" />
                <input type="text" name="friend" /><button class="btn btn-primary" type="submit">Add</button>
            </div>
        </li>
    </ul>
    </form>
    <h2>Pings</h2>
    <ul>
    <?php foreach ($this->profileshowNews as $notification) : ?>
        <li><?= var_export($notification, true) ?></li>
    <?php endforeach; ?>
    </ul>
    <h2>Activities</h2>
    <?php if (isset($this->profileshowActivities)) : ?>
    <?php foreach ($this->profileshowActivities as $activity) : ?>
    <div class="activity">
      <p>
        <a href="<?= $activity['uri'] ?>"><strong><?= $activity['title'] ?></strong></a><br />
        <em><?= $activity['pubDate'] ?></em>
      </p>
      <p>
        <a href="<?= $activity['authorUri'] ?>"><?= $activity['authorUri'] ?></a>
        did <a href="<?= $activity['verb'] ?>"><?= $activity['verb'] ?></a>
        <?php if (isset($activity['objectType'])) : ?>

        an <a href="<?= $activity['objectType'] ?>"><?= $activity['objectType'] ?></a>
        <?php endif; ?>
        : <a href="<?= $activity['object'] ?>"><?= $activity['object'] ?></a>
        <?php if (isset($activity['objectContent'])) : ?>

        <?= $activity['objectContent'] ?>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
    <?php else: ?>
        <div class="well">
        There are not Activities of this person
        </div>
    <?php endif; ?>
    <h2>Add Activity ...</h2>
        <th>Actor</th>
            <?= $this->profileshowName ?>
            <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
        <ul class="nav nav-pills">
            <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
            <li><a href="#link" data-toggle="tab">Link</a></li>
            <li><a href="#photo" data-toggle="tab">Photo</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="status">
                <form method="post" action="?c=activity&a=addactivity">
                    <textarea name="content"></textarea>
                    <input type="hidden" name="verb" value="http://xmlns.notu.be/aair#Post"  >
                    <input type="hidden" name="type" value="http://rdfs.org/sioc/ns#Post" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
            <div class="tab-pane" id="link">
                <form method="post" action="?c=activity&a=addactivity">
                    <input type="text" name="content" /></br>
                    <textarea name="content"></textarea>
                    <input type="hidden" name="verb" value="http://xmlns.notu.be/aair#Share" />
                    <input type="hidden" name="type" value="http://xmlns.notu.be/aair/ns#Link" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
            <div class="tab-pane" id="photo">
                <form method="post" action="?c=activity&a=addactivity">
                    <input type="file" name="photo" /></br>
                    <textarea name="content"></textarea>
                    <input type="hidden" name="verb" value="http://xmlns.notu.be/aair#Share" />
                    <input type="hidden" name="type" value="http://xmlns.notu.be/aair/ns#Photo" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
        </div>
    <a href="?c=feed&amp;a=getFeed&amp;uri=<?= urlencode($this->profileshowPersonUri) ?>">Show Activity Feed</a>
    <form method="post" action="?c=user&a=subscribe">
        <div class="input-append">
            <input type="hidden" name="user" value="<?= $this->profileshowPersonUri ?>" />
            <input type="text" name="feeduri" /><button class="btn btn-primary" type="submit">Subscribe</button>
        </div>
    </form>
</div>
