<h2>Resource</h2>
<?php if(isset($this->resourceshowImage)) : ?> <img class="avatar size128" src="<?= $this->resourceshowImage ?>" /> <?php endif; ?>
<div class="profile">
    <h3><?= $this->profileshowName ?></h3>
    <?php if(isset($this->profileshowNick)) : ?> <h4><?= $this->profileshowNick ?></h4> <?php endif; ?>
    <h5>knows ...</h5>
    <h2>Activities</h2>
    <?php if (isset($this->resourceshowActivities)) : ?>
    <?php foreach ($this->resourceshowActivities as $activity) : ?>
    <div class="activity">
      <p>
        <a href="<?= $activity['uri'] ?>"><strong><?= $activity['title'] ?></strong></a><br />
        <em><?= $activity['pubDate'] ?></em>
      </p>
      <p>
        <a href="<?= htmlentities($activity['authorUri']) ?>">
            <?= htmlentities($activity['authorUri']) ?>
        </a>
        did <a href="<?= htmlentities($activity['verb']) ?>"><?= htmlentities($activity['verb']) ?></a>
        <?php if (isset($activity['objectType'])) : ?>

        an <a href="<?= htmlentities($activity['objectType']) ?>">
            <?= htmlentities($activity['objectType']) ?>
        </a>
        <?php endif; ?>
        : <a href="<?= htmlentities($activity['object']) ?>"><?= htmlentities($activity['object']) ?></a>
        <?php if (isset($activity['objectContent'])) : ?>

        <?= $activity['objectContent'] ?>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
    <?php else: ?>
        <div class="well">
        There are not Activities of this person
        </div>
    <?php endif; ?>
    <h2>Add Activity ...</h2>
        <th>Actor</th>
            <?= $this->profileshowName ?>
            <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
        <ul class="nav nav-pills">
            <li class="active"><a href="#status" data-toggle="tab">Status</a></li>
            <li><a href="#link" data-toggle="tab">Link</a></li>
            <li><a href="#photo" data-toggle="tab">Photo</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="status">
                <form method="post" action="?c=activity&a=addactivity">
                    <textarea name="content"></textarea>
                    <input type="hidden" name="verb" value="http://xmlns.notu.be/aair#Post"  >
                    <input type="hidden" name="type" value="http://xmlns.notu.be/aair#Note" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <button class="btn btn-primary" type="submit">Post</button>
                </form>
            </div>
            <div class="tab-pane" id="link">
                <form method="post" action="?c=activity&a=addactivity">
                    <input type="text" name="content" /></br>
                    <textarea name="about"></textarea>
                    <input type="hidden" name="verb" value="http://xmlns.notu.be/aair#Share" />
                    <input type="hidden" name="type" value="http://xmlns.notu.be/aair#Bookmark" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
            <div class="tab-pane" id="photo">
                <form enctype="multipart/form-data" method="post" action="?c=activity&a=addactivity">
                    <input type="hidden" name="MAX_FILE_SIZE" value="600000" />
                    <input type="file" name="content"/></br>
                    <textarea name="about"></textarea>
                    <input type="hidden" name="verb" value="http://xmlns.notu.be/aair#Share" />
                    <input type="hidden" name="type" value="http://xmlns.notu.be/aair#Photo" />
                    <input type="hidden" name="actor" value="<?= $this->profileshowPersonUri ?>" />
                    <button class="btn btn-primary" type="submit">Share</button>
                </form>
            </div>
        </div>
    <a href="?c=feed&amp;a=getFeed&amp;uri=<?= htmlentities($this->profileshowPersonUri) ?>">Show Activity Feed</a>
    <form method="post" action="?c=user&a=subscribe">
        <div class="input-append">
            <input type="hidden" name="user" value="<?= $this->profileshowPersonUri ?>" />
            <input type="text" name="feeduri" /><button class="btn btn-primary" type="submit">Subscribe</button>
        </div>
    </form>
</div>
